name: token, gogo!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Generate .env
        uses: du5rte/create-secrets-file@v1
        with:
          secrets: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          # optionals
          # file: .env
          # mode: dotenv
          # path: src
      - run: npm i
      - name: eecho
        run: echo ${{ secrets.BOT_TOKEN }}
      - name: Generate
        run: node main.js 
