name: token, gogo!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm i
      - name: Generate
        run: node main.js ${{ env.BOT_TOKEN }}
